"""Storage failures.

Every one of these is raised with a message safe to surface. None carries the
endpoint URL, the access key, the secret, or a signed URL -- a storage error
that quotes its own configuration is how credentials reach a log aggregator.
"""

from __future__ import annotations


class StorageError(Exception):
    """Base class for object storage failures."""


class StorageUnavailableError(StorageError):
    """The storage backend could not be reached or refused the request.

    Raised instead of letting a botocore exception propagate: those carry the
    full request context, including the endpoint and sometimes credentials.
    """


class StorageConfigurationError(StorageError):
    """Storage is not configured usably.

    Raised at the point of use rather than at startup, so a deployment that
    does not touch storage is not blocked by an incomplete storage config.
    """


class ObjectNotFoundError(StorageError):
    """No object exists at that reference."""


class ObjectTooLargeError(StorageError):
    """The payload exceeds the configured maximum object size."""


class UnsupportedContentTypeError(StorageError):
    """The content type is not in the configured allowlist."""


class InvalidObjectKeyError(StorageError):
    """A key was rejected as unsafe or malformed.

    Keys are generated by APEX, never supplied by a caller, so reaching this
    means either a bug or an attempt to address storage directly.
    """
